title: Family Fun Trivia
copyright: JackAce Studios, LLC
copyright_url: https://www.jackace.com
email: info@famfuntrivia.com
description: The kid-friendly podcast perfect for family road trips!
twitter_username: JackAce
github_username: JackAce
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
permalink: /blog/:year/:month/:day/:title/
paginate: 3
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
  - node_modules
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "/assets/images/brand/fft-logo-v3-64x64.jpg"

footer:
  links:
    - label: ""
      icon: "fab fa-brands fa-youtube"
      url: "https://www.youtube.com/@FamFunTrivia"
    - label: ""
      icon: "fab fa-brands fa-spotify"
      url: "https://open.spotify.com/show/0VhK8a53LuYi2h9er9E48r?si=ZP4PLZojScy7LViYuSBFJg"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JackAce/famfuntrivia.com"

# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "familyfuntrivia"

# collections:
#   episodes:
#     output: true
#     permalink: /episodes/:season/:episode

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true 
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# These settings essentially say output index.html files for each portfolio
# document in _portfolio at _site/portfolio/<document-filename>/.
collections:
  essays:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-VGY0FWWP6W" # this doesn't work anymore?
    #anonymize_ip: false # default

cookie_consent_script: "e8fb38e189a1451b64d10d3df700ce06"

# fixes "No GitHub API authentication" error
github: [metadata]

port: 4096
