title: Family Fun Trivia
email: info@famfuntrivia.com
description: The kid-friendly podcast perfect for family road trips!
twitter_username: JackAce
github_username: JackAce
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: air
permalink: /blog/:year/:month/:day/:title/
paginate: 3
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
  - node_modules

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "/assets/images/brand/fft-logo-v2-1024x1024.png"

author:
  name   : "Jack Haze"
  avatar: /assets/images/brand/jack-avatar-v2-1024x1024.png
  bio    : "Software Engineer"
  location : "Southern California"
  links:
    - label: "links.famfuntrivia.com"
      icon: "fas fa-fw fa-link"
      url: "https://links.famfuntrivia.com/"
    - label: "TikTok"
      icon: "fab fa-fw fa-tiktok"
      url: "https://tiktok.com/@jackace.com"
    - label: "Patreon"
      icon: "fab fa-fw fa-patreon"
      url: "https://patreon.com/FamilyFunTrivia"
    - label: "BlueSky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/jackace.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JackAce"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JackAce"

footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/jackace.com"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jackacedotcom"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JackAce"
    - label: ""
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JackAce"

# comments:
#   provider: "disqus"
#   disqus:
#     shortname: "janmeppeblog"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true 
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# These settings essentially say output index.html files for each portfolio
# document in _portfolio at _site/portfolio/<document-filename>/.
collections:
  essays:
    output: true
    permalink: /:collection/:path/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-VGY0FWWP6W" # this doesn't work anymore?
    #anonymize_ip: false # default

cookie_consent_script: "e8fb38e189a1451b64d10d3df700ce06"

# fixes "No GitHub API authentication" error
github: [metadata]

port: 4096
